version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: kochetov98/provectus-test
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: "~/project/devops/02 - dockerfile"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo $DOCKERHUB_TOKEN | docker login -u kochetov98 --password-stdin
            docker build -t $IMAGE_NAME:latest .

            docker build -t $IMAGE_NAME:latest .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1

            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master