version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: kochetov98/provectus-test
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          working_directory: "devops/02\ -\ dockerfile"
          command: |
            echo $DOCKERHUB_TOKEN | docker login -u kochetov98 --password-stdin
            docker build -t $IMAGE_NAME:latest .

            docker build -t $IMAGE_NAME:latest .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1

            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-docker:
    jobs:
      - build